const db = require('../config/db')

db('perfis')
  .then(res => console.log(res))
  .catch(err => console.error(err))
  .finally(() => db.destroy())

db('perfis')
  .then(res => res.map(perfil => perfil.nome))
  .then(res => console.log(res))
  .catch(err => console.error(err))
  .finally(() => db.destroy())

db()
  .select('nome', 'id')
  .from('perfis')
  .limit(4).offset(2)
  .then(res => console.log(res))
  .catch(err => console.error(err))
  .finally(() => db.destroy())

db('perfis')
  .select('id', 'nome')
  .where({ id: 2 })
  // .where('id', '=', 2)
  .first()
  .then(res => console.log(res.nome))
  .finally(() => db.destroy())

db('perfis')
  .select('id', 'nome')
  .where('nome', 'like', '%m%')
  .whereNot({ id: 2 })
  .then(res => console.log(res))
  .finally(() => db.destroy())

db('perfis')
  .select('id', 'nome')
  .whereIn('id', [1, 2, 3])
  .then(res => console.log(res))
  .finally(() => db.destroy())
